LeonardoVNC/Learning-Agent

client/src/components/cursosForm.tsx, client/src/interfaces/claseInterface.ts
- Se agrega el campo de semestre al modal de cursos.
- Validación requerida para Semestre (“Campo requerido”).
=> feat: campo semestre y validación requerida

backend/src/modules/gestion_academica/application/commands/create-enrollment.usecase.ts, backend/src/modules/gestion_academica/application/queries/get-classes-by-student.usecase.ts, backend/src/modules/gestion_academica/application/queries/get-students-by-class.usecase.ts, backend/src/modules/gestion_academica/gestion_academica.module.ts, backend/src/modules/gestion_academica/infrastructure/http/dtos/create-enrollment.dto.ts, backend/src/modules/gestion_academica/infrastructure/http/gestion_academica.controller.ts, backend/src/modules/gestion_academica/tokens.ts
- Se creó un endpoint GET para recuperar todos los cursos de un estudiante, esto a través de su `studentId`
- Se creó un endpoint GET para recuperar todos los estudiantes de un curso, esto a través del id del curso
- Se creó un endpoint POST para relacionar una nueva inscricpión entre estudiante y curso, empleando el ID de ambas entidades.
- Todas estas operaciones se agregan para la tabla `Enrollment`
=> #16 Feat: Crear endpoints para recuperar inscripciones

backend/src/main.ts, backend/src/modules/gestion_academica/application/queries/get-class-by-id.usecase.ts, backend/src/modules/gestion_academica/application/queries/get-students-by-class.usecase.ts, backend/src/modules/gestion_academica/application/queries/response_dtos/UserInfo.dto.ts, backend/src/modules/gestion_academica/gestion_academica.module.ts, backend/src/modules/gestion_academica/infrastructure/http/gestion_academica.controller.ts, client/src/api/apiClient.ts, client/src/components/cursosForm.tsx, client/src/hooks/useClasses.ts, client/src/interfaces/claseInterface.ts, client/src/interfaces/studentInterface.ts, client/src/pages/clasesMenu.tsx, client/src/pages/estudiantesPerClase.tsx, client/src/services/classesService.ts, client/src/services/studentService.ts
- Se habilitaron los CORS para comunicar el front y el back
- Adaptado el API de creación de clases para mantener el DTO de backend
- Mejorado el endpoint de obtención de estudiantes por clase para obtener también su información de usuario
- Adaptado el API de obtención de estudiantes por curso en el frontend
- Agregado un endpoint para cargar la información de estudiantes por curso
>[!Important]
>No se implementaron los datos de asistencia ni notas por parcial en la pantalla del Curso
=> Configuración de las APIs - Front y Back

backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/commands/update-class.usecase.ts, backend/src/modules/academic_management/domain/ports/classes.repository.ports.ts, backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts, backend/src/modules/academic_management/infrastructure/http/dtos/edit-class.dto.ts, backend/src/modules/academic_management/infrastructure/persistence/classes.prisma.repository.ts
- Se agregó un endpoint PUT para poder actualizar la información de un curso encontrado por su ID.
- Se comprueba que el ID enviado sea el de el docente a cargo del curso, caso contrario se niega la edición.
>[!Important]
>Se requiere enviar todos los campos del DTO, sin importar si se actualizan o no
=> Feat: Add edit class endpoint

backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/commands/soft-delete-class.usecase.ts, backend/src/modules/academic_management/domain/ports/classes.repository.ports.ts, backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts, backend/src/modules/academic_management/infrastructure/http/dtos/delete-class.dto.ts, backend/src/modules/academic_management/infrastructure/persistence/classes.prisma.repository.ts
- Se implementa un Endpoint PUT para actualizar el valor `isActive` de una clase.
- La solicitud se procesará solamente si el docente que envía la solicitud es el creador de la clase y si no existen inscripciones en la clase.
>[!Important]
>Las inscripciones tampoco deberían poder borrarse, por lo que se toma en cuenta su atributo `isActive`
- La estructura de la solicitud es la siguiente:
=> Feat: Soft delete to Classes Endpoint

client/src/hooks/useClasses.ts, client/src/layouts/AppLayout.tsx, client/src/pages/clasesMenu.tsx, client/src/pages/estudiantesPerClase.tsx, client/src/routes/routes.tsx
- Se agregaron las rutas pertenecientes al módulo 
- Agregada plantilla de diseño a la página principal del módulo
- Agregada la plantilla de diseño a la página de estudiantes por clase
=> Feat: add class routes to sidebar

client/src/components/cursosForm.tsx, client/src/hooks/useClasses.ts, client/src/pages/clasesMenu.tsx, client/src/services/authService.ts
- Se agregó una conexión al endpoint `auth/me` para recuperar información del usuario a través del Token.
- Se agregó un campo en el formulario para envíar automáticamente el ID del usuario registrado
- Se corrigió el bug que cargaba un ID incorrecto a las cards al momento de crear un nuevo curso
=> Feat: Asignación automática del docente al crear curso

client/src/components/StudentPreviewModal.tsx, client/src/components/studentUpload.tsx, client/src/hooks/useEnrollment.ts, client/src/interfaces/enrollmentInterface.ts, client/src/pages/estudiantesPerClase.tsx, client/src/services/enrollmentService.ts, client/src/utils/studentImport.ts
- Validación de Excel/CSV 
- Integración del endpoint de inscripción grupal con backend 
- Inclusión de modal de previsualización antes de guardar estudiantes
=> feat: implement Excel/CSV validation and backend integration

client/src/pages/CourseDetailPage.tsx, client/src/routes/routes.tsx, client/src/services/teacherService.ts
This pull request introduces a new course detail page to the application and updates the routing accordingly, as well as making a minor import change in the teacher service. The main focus is on improving the user navigation experience for class-related pages.
Routing and page structure improvements:
* Added the `CourseDetailPage` component and updated the route for `/classes/:id` to render this new page instead of the student list. Also introduced a new route `/classes/:id/students` for the student list, making the navigation more intuitive and organized. [[1]](diffhunk://#diff-87dd982dd7a254f939c52a64daece01534437c86cb7c1503dc45bc6238e478c7R11) [[2]](diffhunk://#diff-87dd982dd7a254f939c52a64daece01534437c86cb7c1503dc45bc6238e478c7L29-R31)
Code quality and consistency:
* Changed the …
=> feat: add CourseDetailPage component and update routes

backend/prisma/migrations/20250827022310_academic_courses/migration.sql, backend/prisma/schema.prisma, backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/commands/soft-delete-class.usecase.ts, backend/src/modules/academic_management/application/commands/update-class.usecase.ts, backend/src/modules/academic_management/domain/entities/classes.entity.ts, backend/src/modules/academic_management/domain/entities/course.entity.ts, backend/src/modules/academic_management/domain/ports/classes.repository.ports.ts, backend/src/modules/academic_management/domain/ports/courses.repository.ports.ts, backend/src/modules/academic_management/infrastructure/persistence/classes.prisma.repository.ts, backend/src/modules/academic_management/infrastructure/persistence/course.prisma.repository.ts, backend/src/modules/academic_management/tokens.ts
- Se agrega una tabla Course para almacenar las materias que cree el docente
- Se actualizan las relaciones necesarias para la implementación de la nueva tabla.
- Se corrigen temporalmente algunos endpoints (A corregirse en la siguiente Task)
- Se actualizaron los Ports, Entitys y Repositories de la arquitectura hexagonal
=> US-001 - Update DB

backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/commands/create-course.usecase.ts, backend/src/modules/academic_management/application/queries/get-courses-by-teacher.usecase.ts, backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts, backend/src/modules/academic_management/infrastructure/http/dtos/create-course.dto.ts
- Se agregan 2 endpoints para la creación de materias y la recuperación de estas a través del ID del docente
- Endpoint de creación de materias:
- Endpoint de recuperación de materias por ID del docente:
=> US001 - Feat: Course endpoints

client/src/hooks/useCourses.ts, client/src/interfaces/courseInterface.ts, client/src/services/course.service.ts
- Se agrega una interfaz para administrar la información relacionada a los `Courses` o Materias del docente
- Se agregaron los services correspondientes a los 2 nuevos endpoints planteados en esta US
- Se agregó un Hook para manejar la lógica de creación y obtención de recursos
=> feat[US-001]: create course service and hook for client

backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/commands/create-class.usecase.ts, backend/src/modules/academic_management/application/queries/get-course-by-id.usecase.ts, backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts
- Se agregó un endpoint para recuperar una materia por su ID
- Se actualizó el endpoint de creación de clases para confirmar la existencia de un curso
=> Feat[US001] - Endpoints en nuevo formato

client/src/pages/courses/TeacherCoursePage.tsx, client/src/routes/routes.tsx, client/src/services/course.service.ts
Se añadieron los botones para ir a materiales y los exámenes. Todavía no son funcionales porque se espera que los de sus respectivos módulos los redireccionen como se debe. Igual el card no funciona porque falta la página de la US002
=> feat: Exams and material buttons for each course

client/src/pages/courses/CoursePeriodsPage.tsx
- Added Create Period button in top-right corner of periods view
- Button only visible for users with 'docente' role
- Integrated with existing CreatePeriodForm component
- Modal opens on button click with period creation form
- Added state management for modal (open/close) and loading states
- Connected period creation functionality with useClasses hook
- Auto-refresh period list after successful creation
- Proper error handling during period creation
- Clean UI with primary button styling and PlusOutlined icon
=> feat(Task#72): Add Create Period button and modal functionality

client/src/interfaces/courseInterface.ts, client/src/pages/courses/CoursePeriodsPage.tsx, client/src/pages/courses/CreateCourseForm.tsx, client/src/pages/courses/TeacherCoursePage.tsx
- Se cambiaron las llamadas a service directamente desde las `pages` para asegurar el uso de los hooks y de la respuesta que entregan.
- Se agregó una interfaz DTO para la creación de cursos, esto con el fin de evitar el uso de datos `any` y no provocar problemas con husky más adelante
=> Us006: Hooks error messages

backend/src/modules/academic_management/application/queries/get-students-by-class.usecase.ts, client/src/hooks/useEnrollment.ts, client/src/interfaces/enrollmentInterface.ts, client/src/pages/academic_management/CourseDetailPage.tsx, client/src/services/enrollment.service.ts
- Se agregó la acción de borrado de una inscripción en un período
- Se realizaron las conexiones necesarias para comunicar la función de borrado de inscripciones  con el backend
- Se configuraron los mensajes de confirmación y error a las acciones de borrado
- Se configuró la carga de estudiantes dinámicamente
=> US001: Conexión de Soft-Delete con el backend y cargado dinámico de estudiantes

backend/src/modules/academic_management/academic_management.module.ts, backend/src/modules/academic_management/application/queries/get-date-absences-by-student.usecase.ts.ts, backend/src/modules/academic_management/application/queries/get-student-absences-by-date.usecase.ts.ts, backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts
Agregue un use case llamado get-student-absences-by-date.usecase.ts
Modifique los archivos academic_management.controller donde agregue el endpoint y  academic_management.module donde añadi el usecase
=> feat[004] Endpoint to obtain a student's absence dates

backend/src/modules/academic_management/infrastructure/http/academic_management.controller.ts
Modifique el archivo academic_management.controllers.ts, donde cambie el enpoint de ausencias por clase
=> feat[US004] Changes to the absence endpoint by class

client/src/pages/academic_management/CourseDetailPage.tsx
removi la seccion de materiales en la vista de periodos
=> fix[US005] remove materials button from the period view
